### ISSUE TITLE
Combat system design

### ISSUE THREAD

**Issue by realstealthninja** [BurntToaster-Pirate15/Project-Prometheus#15]
## prometheus's back bone

The "combat" should be pacifist in nature for more information consult general chat

**Comment by nimoooos** [comment]
enemies (shadow creatures) are defeated by restoring them

**Comment by nimoooos** [comment]
[GDD:gameplay-overview](https://github.com/BurntToaster-Pirate15/Project-Prometheus/blob/f5753f756ebf74856cd1bf2d3a392cc6db741c1d/GDD.md#gameplay-overview)
Combat system design first draft complete
