### ISSUE TITLE
Get github pages working

### ISSUE THREAD

**Issue by realstealthninja** [BurntToaster-Pirate15/Project-Prometheus#2]
We could potentially get the game playable on git hub itself using the pages feature

**Comment by nimoooos** [comment]
To do:
* Automatically download artifact from web when it's complete
* Put it on pages through github actions
(they're both easier said than done but whatever)

**Comment by realstealthninja** [comment]
Additional information:
We already have a build action `krynv/build-godot-action@v1.0.0` in godot-ci.yml

**Comment by realstealthninja** [comment]
Github pages does not allow CORS and sharedvertexbuffer thus closing this issue until further developments
